### ISSUE TITLE
Number of words per round

### ISSUE THREAD

**Issue by arjunmahishi** [arjunmahishi/type-test#4]
The User should be able to pick the number of words per round

**Comment by FEDQK** [comment]
I did it, please check my PR #11

**Comment by arjunmahishi** [comment]
Thanks for your intrest @FEDQK!

There seem to be some conflicts in the code. If you can hold off for sometime, I will be merging some more code. You can then rebase you branch and update the PR. Sound good?

**Comment by FEDQK** [comment]
ok, let me know when you're done merging.

**Comment by arjunmahishi** [comment]
Done @FEDQK 
You can go ahead and rebase

**Comment by FEDQK** [comment]
Hi @arjunmahishi 
I updated PR, please check it
